## Definisi Matriks
Matriks adalah susunan bilangan dalam bentuk persegi panjang yang tersusun dalam **baris** dan **kolom**.  
Secara umum, matriks direpresentasikan sebagai berikut:  

\[
A =
\begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn}
\end{bmatrix}
\]

di mana:
- \( m \) = jumlah baris
- \( n \) = jumlah kolom
- \( a_{ij} \) = elemen pada baris ke-\( i \) dan kolom ke-\( j \).

---

## Penjumlahan Matriks
Penjumlahan matriks hanya dapat dilakukan pada **dua matriks dengan ukuran yang sama**.  

Jika \( A \) dan \( B \) adalah matriks **2x2**, maka:

\[
C = A + B =
\begin{bmatrix}
a_{11} + b_{11} & a_{12} + b_{12} \\
a_{21} + b_{21} & a_{22} + b_{22}
\end{bmatrix}
\]

In [5]:
import numpy as np

# Definisi matriks A dan B
A = np.array([[2, 3], [4, 5]])
B = np.array([[1, 2], [3, 4]])

# Penjumlahan Matriks
C = A + B

print("Hasil Penjumlahan Matriks:")
print(C)


Hasil Penjumlahan Matriks:
[[3 5]
 [7 9]]


### Perkalian Matriks 
Perkalian dua matriks hanya bisa dilakukan jika jumlah kolom pada matriks pertama sama dengan jumlah baris pada matriks kedua.

Jika:

\[
C = A \times B =
\begin{bmatrix}
(a_{11} \times b_{11} + a_{12} \times b_{21}) & (a_{11} \times b_{12} + a_{12} \times b_{22}) \\
(a_{21} \times b_{11} + a_{22} \times b_{21}) & (a_{21} \times b_{12} + a_{22} \times b_{22})
\end{bmatrix}
\]


In [6]:
import numpy as np

# Definisi Matriks A dan B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perkalian Matriks
C = np.dot(A, B)

print("Hasil Perkalian Matriks:")
print(C)


Hasil Perkalian Matriks:
[[19 22]
 [43 50]]


### Perkalian Skalar dengan Matrik
Perkalian skalar dengan matriks berarti **mengalikan setiap elemen dalam matriks dengan suatu bilangan skalar**.

Jika \( k \) adalah skalar dan \( A \) adalah matriks, maka:

\[
C = k \times A = k \times
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix}
=
\begin{bmatrix}
k \times a_{11} & k \times a_{12} \\
k \times a_{21} & k \times a_{22}
\end{bmatrix}
\]


In [7]:
import numpy as np

# Definisi skalar dan matriks A
k = 3
A = np.array([[2, 4], [6, 8]])

# Perkalian Skalar dengan Matriks
C = k * A

print("Hasil Perkalian Skalar dengan Matriks:")
print(C)


Hasil Perkalian Skalar dengan Matriks:
[[ 6 12]
 [18 24]]
